# Generated by Django 5.2.9 on 2025-12-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст поради')),
                ('sentiment_threshold', models.FloatField(default=0.0, verbose_name='Поріг (від -1.0)')),
            ],
        ),
    ]
