# Generated by Django 5.2.9 on 2025-12-04 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodrecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
